.class public final Lv4e$a$i;
.super Lsbe;
.source "Twttr"

# interfaces
.implements Lu9b;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lv4e$a;-><init>(Lv4e;)V
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lsbe;",
        "Lu9b<",
        "Lx54;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic E0:Lv4e;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lv4e<",
            "TT;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lv4e;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lv4e<",
            "TT;>;)V"
        }
    .end annotation

    iput-object p1, p0, Lv4e$a$i;->E0:Lv4e;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lsbe;-><init>(I)V

    return-void
.end method


# virtual methods
.method public final invoke()Ljava/lang/Object;
    .locals 4

    .line 1
    iget-object v0, p0, Lv4e$a$i;->E0:Lv4e;

    sget v1, Lv4e;->H0:I

    .line 2
    invoke-virtual {v0}, Lv4e;->E()Lg64;

    move-result-object v0

    .line 3
    iget-object v1, p0, Lv4e$a$i;->E0:Lv4e;

    .line 4
    iget-object v1, v1, Lv4e;->G0:Lyml$b;

    .line 5
    invoke-virtual {v1}, Lyml$b;->invoke()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lv4e$a;

    .line 6
    iget-object v1, v1, Le5e$b;->a:Lyml$a;

    sget-object v2, Le5e$b;->b:[Lc6e;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    .line 7
    invoke-virtual {v1}, Lyml$a;->invoke()Ljava/lang/Object;

    move-result-object v1

    const-string v2, "<get-moduleData>(...)"

    .line 8
    invoke-static {v1, v2}, Lahd;->e(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, Lixn;

    .line 9
    iget-boolean v2, v0, Lg64;->c:Z

    if-eqz v2, :cond_0

    .line 10
    iget-object v1, v1, Lixn;->a:Lyc8;

    .line 11
    invoke-virtual {v1, v0}, Lyc8;->b(Lg64;)Lx54;

    move-result-object v0

    goto :goto_0

    .line 12
    :cond_0
    iget-object v1, v1, Lixn;->a:Lyc8;

    .line 13
    iget-object v1, v1, Lyc8;->b:Lwzg;

    .line 14
    invoke-static {v1, v0}, Lhha;->a(Lwzg;Lg64;)Lx54;

    move-result-object v0

    :goto_0
    if-nez v0, :cond_3

    .line 15
    iget-object v0, p0, Lv4e$a$i;->E0:Lv4e;

    .line 16
    sget-object v1, Luml;->c:Luml$a;

    .line 17
    iget-object v2, v0, Lv4e;->F0:Ljava/lang/Class;

    .line 18
    invoke-virtual {v1, v2}, Luml$a;->a(Ljava/lang/Class;)Luml;

    move-result-object v1

    if-eqz v1, :cond_1

    .line 19
    iget-object v1, v1, Luml;->b:Ls9e;

    if-eqz v1, :cond_1

    .line 20
    iget-object v1, v1, Ls9e;->a:Ls9e$a;

    goto :goto_1

    :cond_1
    const/4 v1, 0x0

    :goto_1
    if-nez v1, :cond_2

    const/4 v2, -0x1

    goto :goto_2

    .line 21
    :cond_2
    sget-object v2, Lv4e$b;->a:[I

    invoke-virtual {v1}, Ljava/lang/Enum;->ordinal()I

    move-result v3

    aget v2, v2, v3

    :goto_2
    packed-switch v2, :pswitch_data_0

    .line 22
    :pswitch_0
    new-instance v0, Lkotlin/NoWhenBranchMatchedException;

    invoke-direct {v0}, Lkotlin/NoWhenBranchMatchedException;-><init>()V

    throw v0

    .line 23
    :pswitch_1
    new-instance v2, Lx9e;

    const-string v3, "Unknown class: "

    .line 24
    invoke-static {v3}, Lwlg;->b(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v3

    .line 25
    iget-object v0, v0, Lv4e;->F0:Ljava/lang/Class;

    .line 26
    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string v0, " (kind = "

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 v0, 0x29

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v2, v0}, Lx9e;-><init>(Ljava/lang/String;)V

    throw v2

    .line 27
    :pswitch_2
    new-instance v1, Ljava/lang/UnsupportedOperationException;

    const-string v2, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "

    .line 28
    invoke-static {v2}, Lwlg;->b(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 29
    iget-object v0, v0, Lv4e;->F0:Ljava/lang/Class;

    .line 30
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 31
    invoke-direct {v1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v1

    .line 32
    :pswitch_3
    new-instance v1, Ljava/lang/UnsupportedOperationException;

    const-string v2, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "

    .line 33
    invoke-static {v2}, Lwlg;->b(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 34
    iget-object v0, v0, Lv4e;->F0:Ljava/lang/Class;

    .line 35
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 36
    invoke-direct {v1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v1

    .line 37
    :pswitch_4
    new-instance v1, Lx9e;

    const-string v2, "Unresolved class: "

    .line 38
    invoke-static {v2}, Lwlg;->b(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 39
    iget-object v0, v0, Lv4e;->F0:Ljava/lang/Class;

    .line 40
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v1, v0}, Lx9e;-><init>(Ljava/lang/String;)V

    throw v1

    :cond_3
    return-object v0

    :pswitch_data_0
    .packed-switch -0x1
        :pswitch_4
        :pswitch_0
        :pswitch_3
        :pswitch_3
        :pswitch_3
        :pswitch_2
        :pswitch_1
        :pswitch_4
    .end packed-switch
.end method
